#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# SETUP DEX FOR OIDC
#=================================================
setup_dex

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

# If you need to, you can define custom settings
# (or remove this section entirely if not relevant for you)
redis_db=$(ynh_redis_get_free_db)
redis-cli -n "$redis_db" SET __YNH_PROVISIONED "$app"
django_secret_key=$(ynh_string_random -l 32)
ynh_app_setting_set --key=redis_db --value=$redis_db
ynh_app_setting_set --key=celery_redis_db --value=-1
ynh_app_setting_set --key=django_secret_key --value=$django_secret_key
celery_broker_url=$(get_celery_broker_url)

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Creating S3 Bucket"

s3="${s3:-minio}"

if [[ "${s3}" =~ minio* ]]; then
    s3_domain=$(ynh_app_setting_get --app="$s3" --key=domain)
    s3_password=$(ynh_string_random -l 32)
    s3_user=$app

    # FIXME: this script is currently in PR for the MinIO app:
    # https://github.com/YunoHost-Apps/minio_ynh/pull/77
    sudo -u minio "./setup_app_bucket.sh" --app="$app" --secret="$s3_password" --with-versioning

    ynh_app_setting_set --key="s3_domain" --value="$s3_domain"
    ynh_app_setting_set --key="s3_user" --value="$s3_user"
    ynh_app_setting_set --key="s3_password" --value="$s3_password"
elif [[ "${s3}" =~ seaweedfs* ]]; then
    s3_domain=$(ynh_app_setting_get --app="$s3" --key=domain)
    s3_password=$(ynh_string_random -l 32)
    s3_user=$app

    ynh_app_setting_set --key="s3_domain" --value="$s3_domain"
    ynh_app_setting_set --key="s3_user" --value="$s3_user"
    ynh_app_setting_set --key="s3_password" --value="$s3_password"
else
    ynh_die "garage not yet supported"
fi

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_hide_warnings corepack enable && corepack prepare yarn@latest --activate

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up backend source files..."

ynh_setup_source --dest_dir="$install_dir"

ynh_exec_as_app mkdir -p "$install_dir/_build/venv"
ynh_exec_as_app mkdir -p "$install_dir/_build/frontend"
ynh_exec_as_app mkdir -p "$install_dir/_build/data/static"

pushd "$install_dir/_build/venv"
    ynh_exec_as_app python3 -m venv .
    ynh_hide_warnings ynh_exec_as_app ./bin/pip3 install "$install_dir/src/backend"
    ynh_hide_warnings ynh_exec_as_app ./bin/pip3 freeze > requirements.txt
    ynh_hide_warnings ynh_exec_as_app ./bin/pip3 install -r requirements.txt
popd

# Mail builder
pushd "$install_dir/src/mail"
    ynh_hide_warnings ynh_exec_as_app yarn install --frozen-lockfile
    ynh_hide_warnings ynh_exec_as_app NODE_ENV=production yarn build
popd

pushd "$install_dir/src/backend"
    # Collect the static resources
    ynh_exec_as_app DATA_DIR="$install_dir/_build/data" DJANGO_CONFIGURATION=Build DJANGO_JWT_PRIVATE_SIGNING_KEY=Dummy \
        STATIC_ROOT="$install_dir/src/backend" \
        "$install_dir/_build/venv/bin/python" manage.py collectstatic --noinput

    # Generate compiled translation messages
    ynh_exec_as_app DJANGO_CONFIGURATION=Build \
        "$install_dir/_build/venv/bin/python" manage.py compilemessages

    rdfind -makesymlinks true -followsymlinks true -makeresultsfile false "$install_dir/_build/data/static"
    ynh_psql_db_shell <<< "ALTER USER $db_name WITH SUPERUSER;"
    # Setup the database
    ynh_hide_warnings ynh_exec_as_app \
        DJANGO_CONFIGURATION=Production \
        DB_NAME=$db_name DB_USER=$db_name DB_PASSWORD=$db_pwd \
        "$install_dir/_build/venv/bin/python" manage.py migrate
    ynh_psql_db_shell <<< "ALTER USER $db_name WITH NOSUPERUSER;"

    # Move templates to where they are expected by impress settings
    mv ../backend/core/templates "$install_dir/_build/venv/lib/"python3*/"site-packages/"
popd

ynh_script_progression "Setting up frontend source files..."

pushd "$install_dir/src/frontend"
    ynh_hide_warnings ynh_exec_as_app yarn install
    ynh_hide_warnings ynh_exec_as_app yarn next telemetry disable
    pushd "./apps/impress"
        ynh_hide_warnings ynh_exec_as_app NODE_ENV=production NEXT_PUBLIC_PUBLISH_AS_MIT=false yarn next build --no-lint
    popd
    mv ./apps/impress/out "$install_dir/_build/frontend"
popd

chown -R "$app:www-data" "$install_dir"

#=================================================
# BUILD YARN DEPENDENCIES YJS
#=================================================
ynh_script_progression "Setting up y-provider source files..."

y_provider_api_key=$(ynh_string_random -l 32)
collaboration_server_secret=$(ynh_string_random -l 32)
ynh_app_setting_set --key=y_provider_api_key --value=$y_provider_api_key
ynh_app_setting_set --key=collaboration_server_secret --value=$collaboration_server_secret

pushd "$install_dir/src/frontend/servers/y-provider"
    ynh_hide_warnings ynh_exec_as_app yarn install --pure-lockfile
    ynh_hide_warnings ynh_exec_as_app yarn build
    ynh_hide_warnings ynh_exec_as_app yarn cache clean
popd

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="env" --destination="$install_dir/.env"
chmod 400 "$install_dir/.env"
chown "$app:$app" "$install_dir/.env"

# YJS
ynh_config_add --template="env_yjs" --destination="$install_dir/.env_yjs"
chmod 400 "$install_dir/.env_yjs"
chown "$app:$app" "$install_dir/.env_yjs"

ynh_config_add --template="docs-conf.py" --destination="$install_dir/docs-conf.py"
chmod 400 "$install_dir/docs-conf.py"
chown "$app:$app" "$install_dir/docs-conf.py"

ynh_psql_db_shell "$db_name" <<< "update django_site set domain='https://$domain', name='$domain' where id=1;"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd
ynh_config_add_systemd --service="${app}-yprovider" --template="systemd-yprovider.service"

yunohost service add "$app" --description="Simple collaborative notetaking" --log="/var/log/$app/$app.log"
yunohost service add "$app-yprovider" --description="Yprovider for Docs (La Suite)" --log="/var/log/$app/$app-yprovider.log"

# Stupid trick to avoid a warning from the CI
if false; then
    yunohost service add "$app-celery" --description="Celery for Docs (La Suite)" --log="/var/log/$app/$app-celery.log"
fi

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start"
ynh_systemctl --service="$app-yprovider" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
