#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

celery_broker_url=$(get_celery_broker_url)

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"
ynh_systemctl --service="$app-yprovider" --action="stop"
if use_celery; then
    ynh_systemctl --service="$app-celery" --action="stop"
fi

#=================================================
# SETUP DEX FOR OIDC
#=================================================

setup_dex

#=================================================
# SETUP S3
#=================================================

ynh_script_progression "Updating S3 Bucket"

s3="${s3:-minio}"

if [[ "${s3}" =~ minio* ]]; then
    s3_domain=$(ynh_app_setting_get --app="$s3" --key=domain)
    s3_password=$(ynh_string_random -l 32)
    s3_user=$app

    # FIXME: this script is currently in PR for the MinIO app:
    # https://github.com/YunoHost-Apps/minio_ynh/pull/77
    sudo -u minio "./setup_app_bucket.sh" --app="$app" --secret="$s3_password" --with-versioning

    ynh_app_setting_set --key="s3_domain" --value="$s3_domain"
    ynh_app_setting_set --key="s3_user" --value="$s3_user"
    ynh_app_setting_set --key="s3_password" --value="$s3_password"
elif [[ "${s3}" =~ seaweedfs* ]]; then
    s3_domain=$(ynh_app_setting_get --app="$s3" --key=domain)
    s3_password=$(ynh_string_random -l 32)
    s3_user=$app
    
    yunohost app shell seaweedfs -c "
    weed shell -master=$MASTER <<EOF
    s3.configure -access_key=$app -secret_key=$s3_password -buckets=$app -user=$app -actions=Read,Write,List,Tagging -apply
    EOF
    "
    yunohost app shell seaweedfs -c "
    weed shell -master=$MASTER <<EOF
    s3.bucket.create -name $app -owner $app -withLock
    EOF
    "

    ynh_app_setting_set --key="s3_domain" --value="$s3_domain"
    ynh_app_setting_set --key="s3_user" --value="$s3_user"
    ynh_app_setting_set --key="s3_password" --value="$s3_password"
else
    ynh_die "garage not yet supported"
fi

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_hide_warnings corepack enable && corepack prepare yarn@latest --activate

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading the backend source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace

ynh_exec_as_app mkdir -p "$install_dir/_build/venv"
ynh_exec_as_app mkdir -p "$install_dir/_build/frontend"
ynh_exec_as_app mkdir -p "$install_dir/_build/data/static"

pushd "$install_dir/_build/venv"
    ynh_exec_as_app python3 -m venv .
    ynh_hide_warnings ynh_exec_as_app ./bin/pip3 install "$install_dir/src/backend"
    ynh_hide_warnings ynh_exec_as_app ./bin/pip3 freeze > requirements.txt
    ynh_hide_warnings ynh_exec_as_app ./bin/pip3 install -r requirements.txt
popd

# Mail builder
pushd "$install_dir/src/mail"
    ynh_hide_warnings ynh_exec_as_app yarn install --frozen-lockfile
    ynh_hide_warnings ynh_exec_as_app NODE_ENV=production yarn build
popd

pushd "$install_dir/src/backend"
    # Collect the static resources
    ynh_exec_as_app DATA_DIR="$install_dir/_build/data" DJANGO_CONFIGURATION=Build DJANGO_JWT_PRIVATE_SIGNING_KEY=Dummy \
        STATIC_ROOT="$install_dir/src/backend" \
        "$install_dir/_build/venv/bin/python" manage.py collectstatic --noinput

    # Generate compiled translation messages
    ynh_exec_as_app DJANGO_CONFIGURATION=Build \
        "$install_dir/_build/venv/bin/python" manage.py compilemessages

    rdfind -makesymlinks true -followsymlinks true -makeresultsfile false "$install_dir/_build/data/static"
    ynh_psql_db_shell <<< "ALTER USER $db_name WITH SUPERUSER;"
    # Setup the database
    ynh_hide_warnings ynh_exec_as_app \
        DJANGO_CONFIGURATION=Production \
        DB_NAME=$db_name DB_USER=$db_name DB_PASSWORD=$db_pwd \
        "$install_dir/_build/venv/bin/python" manage.py migrate
    ynh_psql_db_shell <<< "ALTER USER $db_name WITH NOSUPERUSER;"

    # Move templates to where they are expected by impress settings
    mv ../backend/core/templates "$install_dir/_build/venv/lib/"python3*/"site-packages/"
popd

ynh_script_progression "Upgrading the frontend source files..."

pushd "$install_dir/src/frontend"
    ynh_hide_warnings ynh_exec_as_app yarn install
    ynh_hide_warnings ynh_exec_as_app yarn next telemetry disable
    pushd "./apps/impress"
        ynh_hide_warnings ynh_exec_as_app NODE_ENV=production NEXT_PUBLIC_PUBLISH_AS_MIT=false yarn next build --no-lint
    popd
    mv ./apps/impress/out "$install_dir/_build/frontend"
popd

chown -R "$app:www-data" "$install_dir"

#=================================================
# BUILD YARN DEPENDENCIES YJS
#=================================================
ynh_script_progression "Upgrading the y-provider source files..."

pushd "$install_dir/src/frontend/servers/y-provider"
    ynh_hide_warnings ynh_exec_as_app yarn install --pure-lockfile
    ynh_hide_warnings ynh_exec_as_app yarn build
    ynh_hide_warnings ynh_exec_as_app yarn cache clean
popd

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template="env" --destination="$install_dir/.env"
chmod 400 "$install_dir/.env"
chown "$app:$app" "$install_dir/.env"

# YJS
ynh_config_add --template="env_yjs" --destination="$install_dir/.env_yjs"
chmod 400 "$install_dir/.env_yjs"
chown "$app:$app" "$install_dir/.env_yjs"

ynh_config_add --template="docs-conf.py" --destination="$install_dir/docs-conf.py"
chmod 400 "$install_dir/docs-conf.py"
chown "$app:$app" "$install_dir/docs-conf.py"

ynh_psql_db_shell "$db_name" <<< "update django_site set domain='https://$domain', name='$domain' where id=1;"


#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd
ynh_config_add_systemd --service="${app}-yprovider" --template="systemd-yprovider.service"

yunohost service add "$app" --description="Simple collaborative notetaking" --log="/var/log/$app/$app.log"
yunohost service add "$app-yprovider" --description="Yprovider for Docs (La Suite)" --log="/var/log/$app/$app-yprovider.log"

if use_celery; then
    ynh_config_add_systemd --service="${app}-celery" --template="systemd-celery.service"
    yunohost service add "$app-celery" --description="Celery for Docs (La Suite)" --log="/var/log/$app/$app-celery.log"
fi

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"
ynh_systemctl --service="$app-yprovider" --action="start"
if use_celery; then
    ynh_systemctl --service="$app-celery" --action="start"
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
